-- Rotina Pet v2 — execute no SQL Editor do Supabase.
create extension if not exists pgcrypto;
create table if not exists public.pets(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null check(char_length(name) between 1 and 60),species text not null default 'cat' check(species in('cat','dog')),icon text not null default '🐈',active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.weight_entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,pet_id uuid not null references public.pets(id) on delete cascade,recorded_at date not null default current_date,weight_kg numeric(7,3) not null check(weight_kg>0),notes text,created_at timestamptz not null default now());
create table if not exists public.foods(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null check(char_length(name) between 1 and 100),default_unit text not null default 'g' check(default_unit in('g','ml','sachet','can','scoop','unit')),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.diet_plans(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,pet_id uuid not null references public.pets(id) on delete cascade,name text not null,starts_on date not null,ends_on date,active boolean not null default true,created_at timestamptz not null default now(),check(ends_on is null or ends_on>=starts_on));
create table if not exists public.meal_templates(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,diet_plan_id uuid not null references public.diet_plans(id) on delete cascade,scheduled_time time not null,sequence integer not null check(sequence>0),created_at timestamptz not null default now(),unique(diet_plan_id,sequence));
create table if not exists public.plan_foods(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,diet_plan_id uuid not null references public.diet_plans(id) on delete cascade,food_id uuid not null references public.foods(id),daily_quantity numeric(10,3) not null check(daily_quantity>0),unit text not null check(unit in('g','ml','sachet','can','scoop','unit')),meal_sequences integer[] not null,created_at timestamptz not null default now(),unique(diet_plan_id,food_id));
create table if not exists public.meal_components(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,meal_template_id uuid not null references public.meal_templates(id) on delete cascade,food_id uuid not null references public.foods(id),quantity numeric(10,3) not null check(quantity>0),unit text not null check(unit in('g','ml','sachet','can','scoop','unit')),created_at timestamptz not null default now());
create table if not exists public.meal_occurrences(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,pet_id uuid not null references public.pets(id) on delete cascade,meal_template_id uuid not null references public.meal_templates(id) on delete cascade,local_date date not null,scheduled_at timestamptz not null,status text not null default 'pending' check(status in('pending','completed','skipped')),consumption_level text check(consumption_level is null or consumption_level in('full','almost','half','little','none')),completed_at timestamptz,notes text,created_at timestamptz not null default now(),unique(meal_template_id,local_date));
create index if not exists weight_entries_pet_date_idx on public.weight_entries(pet_id,recorded_at desc);create index if not exists foods_user_name_idx on public.foods(user_id,name);create index if not exists plans_pet_start_idx on public.diet_plans(pet_id,starts_on desc);create index if not exists occurrences_pet_date_idx on public.meal_occurrences(pet_id,local_date);
alter table public.pets enable row level security;alter table public.weight_entries enable row level security;alter table public.foods enable row level security;alter table public.diet_plans enable row level security;alter table public.meal_templates enable row level security;alter table public.plan_foods enable row level security;alter table public.meal_components enable row level security;alter table public.meal_occurrences enable row level security;
do $$ declare t text;begin foreach t in array array['pets','weight_entries','foods','diet_plans','meal_templates','plan_foods','meal_components','meal_occurrences'] loop execute format('drop policy if exists "Own rows select" on public.%I',t);execute format('drop policy if exists "Own rows insert" on public.%I',t);execute format('drop policy if exists "Own rows update" on public.%I',t);execute format('drop policy if exists "Own rows delete" on public.%I',t);execute format('create policy "Own rows select" on public.%I for select to authenticated using ((select auth.uid())=user_id)',t);execute format('create policy "Own rows insert" on public.%I for insert to authenticated with check ((select auth.uid())=user_id)',t);execute format('create policy "Own rows update" on public.%I for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id)',t);execute format('create policy "Own rows delete" on public.%I for delete to authenticated using ((select auth.uid())=user_id)',t);end loop;end $$;
create or replace function public.save_diet_plan(p_pet_id uuid,p_name text,p_starts_on date,p_meal_times text[],p_foods jsonb)returns uuid language plpgsql security invoker set search_path=public as $$
declare v_user uuid:=auth.uid();v_plan uuid;v_time text;v_sequence integer:=0;v_food jsonb;v_meal_sequence integer;v_selected_count integer;v_base numeric(10,3);v_quantity numeric(10,3);v_template uuid;v_last_sequence integer;
begin
if v_user is null then raise exception 'Usuário não autenticado';end if;if not exists(select 1 from public.pets where id=p_pet_id and user_id=v_user and active)then raise exception 'Animal não encontrado';end if;if coalesce(array_length(p_meal_times,1),0)=0 then raise exception 'Informe os horários';end if;if jsonb_array_length(p_foods)=0 then raise exception 'Informe ao menos um alimento';end if;
update public.diet_plans set active=false,ends_on=case when starts_on<p_starts_on then p_starts_on-1 else starts_on end where pet_id=p_pet_id and user_id=v_user and active=true;
insert into public.diet_plans(user_id,pet_id,name,starts_on,active)values(v_user,p_pet_id,coalesce(nullif(trim(p_name),''),'Plano alimentar'),p_starts_on,true)returning id into v_plan;
foreach v_time in array p_meal_times loop v_sequence:=v_sequence+1;insert into public.meal_templates(user_id,diet_plan_id,scheduled_time,sequence)values(v_user,v_plan,v_time::time,v_sequence);end loop;
for v_food in select * from jsonb_array_elements(p_foods) loop v_selected_count:=jsonb_array_length(v_food->'meal_sequences');if v_selected_count<1 then raise exception 'Selecione ao menos uma refeição para cada alimento';end if;insert into public.plan_foods(user_id,diet_plan_id,food_id,daily_quantity,unit,meal_sequences)values(v_user,v_plan,(v_food->>'food_id')::uuid,(v_food->>'daily_quantity')::numeric,v_food->>'unit',array(select jsonb_array_elements_text(v_food->'meal_sequences')::integer));v_base:=round((v_food->>'daily_quantity')::numeric/v_selected_count,3);select max(value::integer) into v_last_sequence from jsonb_array_elements_text(v_food->'meal_sequences');for v_meal_sequence in select jsonb_array_elements_text(v_food->'meal_sequences')::integer loop select id into v_template from public.meal_templates where diet_plan_id=v_plan and sequence=v_meal_sequence;if v_template is null then raise exception 'Refeição inválida';end if;if v_meal_sequence=v_last_sequence then v_quantity:=(v_food->>'daily_quantity')::numeric-v_base*(v_selected_count-1);else v_quantity:=v_base;end if;insert into public.meal_components(user_id,meal_template_id,food_id,quantity,unit)values(v_user,v_template,(v_food->>'food_id')::uuid,v_quantity,v_food->>'unit');end loop;end loop;return v_plan;end;$$;
grant execute on function public.save_diet_plan(uuid,text,date,text[],jsonb) to authenticated;

-- Atualização idempotente para bancos criados por versões anteriores.
alter table public.meal_occurrences add column if not exists consumption_level text;
alter table public.meal_occurrences drop constraint if exists meal_occurrences_consumption_level_check;
alter table public.meal_occurrences add constraint meal_occurrences_consumption_level_check check(consumption_level is null or consumption_level in('full','almost','half','little','none'));
update public.meal_occurrences set consumption_level='full' where status='completed' and consumption_level is null;
update public.meal_occurrences set consumption_level=null where status in('pending','skipped') and consumption_level is not null;
comment on column public.meal_occurrences.consumption_level is 'Consumo aproximado registrado pelo tutor: full, almost, half, little ou none.';
